name: Docker build and push

on:
  push:
    branches:
      - dev

jobs:
  publish:
    name: Build and push docker images
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{secrets.github_token}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push tracker
        uses: docker/build-push-action@v2
        with:
          context: ./src/Tracker/.
          file: ./src/Tracker/Tracker/Dockerfile
          push: true
          tags: xfilefin/battletracker-tracker:dev-${{ steps.buildnumber.outputs.build_number }},xfilefin/battletracker-tracker:dev-latest
      - name: Build and push discord integration
        uses: docker/build-push-action@v2
        with:
          context: ./src/discord-integration/.
          file: ./src/discord-integration/Dockerfile
          push: true
          tags: xfilefin/battletracker-discord:dev-${{ steps.buildnumber.outputs.build_number }},xfilefin/battletracker-discord:dev-latest
      - name: Build and push discord integration
        uses: docker/build-push-action@v2
        with:
          context: ./src/rcon-connector/.
          file: ./src/rcon-connector/Dockerfile
          push: true
          tags: xfilefin/battletracker-rconconnector:dev-${{ steps.buildnumber.outputs.build_number }},xfilefin/battletracker-rconconnector:dev-latest
      # - name: Invoke deployment hook
      #   uses: distributhor/workflow-webhook@v1
      #   env:
      #     webhook_url: ${{ secrets.WEBHOOK_URL }}
      #     webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      #     data: '{ "commit_tag": "dev-${{ steps.buildnumber.outputs.build_number }}" }'
    